services:
  memoana:
    image: ${DOCKER_REGISTRY-}memoana
    build:
      context: .
      dockerfile: src/MemoAna.Backend/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 80
      ASPNETCORE_HTTPS_PORTS: 443
      ConnectionStrings__MemoAnaDB: "Host=memoana-db;Port=5432;Database=${POSTGRES_DB:-MemoAnaDB};Username=${POSTGRES_USER:-memoana};Password=${POSTGRES_PASSWORD:-M3M0@n@}" 
      Jwt__Key: ${JWT_KEY:-"5t8iai8+8U6+KkWe7A/FMMjOQsKVik/JVR2TedmbM2XSdwn3pKQ+AKFloMlE1gBKq8Pi/Yl6GzyYxSCMeTLatQ=="}
      ASPNETCORE_Kestrel__Certificates__Default__Path: /root/memoana.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${CERT_PASSWORD:-"M3M0@n@"}
    ports:
      - "8000:80"
      - "8443:443"
    networks:
      - memoana
    depends_on:
      - memoana-db
    volumes:
      - memoana-data:/app/
      - memoana-protection-keys:/root:ro 
      - ./certs/memoana.pfx:/root/memoana.pfx:ro
      - ./certs/memoana.crt:/root/memoana.crt:ro 
  memoana-db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-memoana}}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-M3M0@n@}}
      POSTGRES_DB: ${POSTGRES_DB:-MemoAnaDB}
    ports:
      - "5432:5432"
    networks:
      - memoana
    volumes:
      - memoana-db-data:/var/lib/postgresql/data   
    
volumes:
  memoana-data:
    driver: local
  memoana-protection-keys:
    driver: local
  memoana-db-data:
    driver: local

networks:
  memoana:
    driver: bridge