<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>9744d610-556e-406b-aab4-2446776d1046</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
    <DockerComposeProjectPath>..\..\..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference> 
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.24.1-preview.1" />
    <PackageReference Include="MudBlazor" Version="9.8.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.20" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\MemoAna.Backend.Application\MemoAna.Backend.Application.csproj" />
    <ProjectReference Include="..\MemoAna.Backend.Composition\MemoAna.Backend.Composition.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <Folder Include="Composition\" />
  </ItemGroup>
</Project>
