<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFrameworks>net10.0-android</TargetFrameworks>
    <TargetFrameworks Condition="!$([MSBuild]::IsOSPlatform('linux'))">$(TargetFrameworks);net10.0-ios;net10.0-maccatalyst</TargetFrameworks>
    <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net10.0-windows10.0.19041.0</TargetFrameworks>

    <!-- Note for MacCatalyst:
            The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
            When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
            The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
            either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
    <!-- For example: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers> -->

    <OutputType>Exe</OutputType>
    <RootNamespace>MemoAna</RootNamespace>
    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultCssItems>false</EnableDefaultCssItems>
    <Nullable>enable</Nullable>

    <!-- Enable XAML source generation for faster build times and improved performance.
             This generates C# code from XAML at compile time instead of runtime inflation.
             To disable, remove this line.
             For individual files, you can override by setting Inflator metadata:
               <MauiXaml Update="MyPage.xaml" Inflator="Default" /> (reverts to defaults: Runtime for Debug, XamlC for Release)
               <MauiXaml Update="MyPage.xaml" Inflator="Runtime" /> (force runtime inflation) -->
    <MauiXamlInflator>SourceGen</MauiXamlInflator>

    <!-- Display name -->
    <ApplicationTitle>MemoAna</ApplicationTitle>

    <!-- App Identifier -->
    <ApplicationId>com.remotecodehub.memoana</ApplicationId>

    <!-- Versions -->
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>

    <!-- To develop, package, and publish an app to the Microsoft Store, see: https://aka.ms/MauiTemplateUnpackaged -->
    <WindowsPackageType>None</WindowsPackageType>

    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">24.0</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
    <TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
  </PropertyGroup>

  <ItemGroup>
    <!-- App Icon -->
    <MauiIcon Include="Resources\AppIcon\appicon.svg" Color="#512BD4">
      <ForegroundScale>0.65</ForegroundScale>
    </MauiIcon>

    <!-- Splash Screen -->
    <MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />

    <!-- Images -->
    <MauiImage Include="Resources\Images\*" />
    <MauiImage Update="Resources\Images\dotnet_bot.svg" BaseSize="168,208" />

    <!-- Custom Fonts -->
    <MauiFont Include="Resources\Fonts\*" />

    <!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
    <MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <AndroidResource Remove="ViewModels\**" />
    <Compile Remove="ViewModels\**" />
    <Content Remove="ViewModels\**" />
    <EmbeddedResource Remove="ViewModels\**" />
    <MauiXaml Remove="ViewModels\**" />
    <None Remove="ViewModels\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="wwwroot\fonts\Gwenchana.ttf" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Seed\disney\d01_disney.jpg" />
    <EmbeddedResource Include="Resources\Seed\disney\d02_disney.jpg" />
    <EmbeddedResource Include="Resources\Seed\disney\d03_disney.jpg" />
    <EmbeddedResource Include="Resources\Seed\disney\d04_disney.jpg" />
    <EmbeddedResource Include="Resources\Seed\disney\d05_disney.jpg" />
    <EmbeddedResource Include="Resources\Seed\disney\d06_disney.jpg" />
    <EmbeddedResource Include="Resources\Seed\disney\d07_disney.jpg" />
    <EmbeddedResource Include="Resources\Seed\disney\d08_disney.jpg" />
    <EmbeddedResource Include="Resources\Seed\disney\d09_disney.jpg" />
    <EmbeddedResource Include="Resources\Seed\disney\d10_disney.jpg" />
    <EmbeddedResource Include="Resources\Seed\disney\d11_disney.jpg" />
    <EmbeddedResource Include="Resources\Seed\disney\d12_disney.jpg" />
    <EmbeddedResource Include="Resources\Seed\disney\d13_disney.jpg" />
    <EmbeddedResource Include="Resources\Seed\disney\d14_disney.jpg" />
    <EmbeddedResource Include="Resources\Seed\disney\d15_disney.jpg" />
    <EmbeddedResource Include="Resources\Seed\marvel\m01_marvel.jpg" />
    <EmbeddedResource Include="Resources\Seed\marvel\m02_marvel.jpg" />
    <EmbeddedResource Include="Resources\Seed\marvel\m03_marvel.jpg" />
    <EmbeddedResource Include="Resources\Seed\marvel\m04_marvel.jpg" />
    <EmbeddedResource Include="Resources\Seed\marvel\m05_marvel.jpg" />
    <EmbeddedResource Include="Resources\Seed\marvel\m06_marvel.jpg" />
    <EmbeddedResource Include="Resources\Seed\marvel\m07_marvel.jpg" />
    <EmbeddedResource Include="Resources\Seed\marvel\m08_marvel.jpg" />
    <EmbeddedResource Include="Resources\Seed\marvel\m09_marvel.jpg" />
    <EmbeddedResource Include="Resources\Seed\marvel\m10_marvel.jpg" />
    <EmbeddedResource Include="Resources\Seed\marvel\m11_marvel.jpg" />
    <EmbeddedResource Include="Resources\Seed\marvel\m12_marvel.jpg" />
    <EmbeddedResource Include="Resources\Seed\marvel\m13_marvel.jpg" />
    <EmbeddedResource Include="Resources\Seed\marvel\m14_marvel.jpg" />
    <EmbeddedResource Include="Resources\Seed\marvel\m15_marvel.jpg" />
    <EmbeddedResource Include="Resources\Seed\pokemon\p01_pokemon.png" />
    <EmbeddedResource Include="Resources\Seed\pokemon\p02_pokemon.png" />
    <EmbeddedResource Include="Resources\Seed\pokemon\p03_pokemon.png" />
    <EmbeddedResource Include="Resources\Seed\pokemon\p04_pokemon.png" />
    <EmbeddedResource Include="Resources\Seed\pokemon\p05_pokemon.png" />
    <EmbeddedResource Include="Resources\Seed\pokemon\p06_pokemon.png" />
    <EmbeddedResource Include="Resources\Seed\pokemon\p07_pokemon.png" />
    <EmbeddedResource Include="Resources\Seed\pokemon\p08_pokemon.png" />
    <EmbeddedResource Include="Resources\Seed\pokemon\p09_pokemon.png" />
    <EmbeddedResource Include="Resources\Seed\pokemon\p10_pokemon.png" />
    <EmbeddedResource Include="Resources\Seed\pokemon\p11_pokemon.png" />
    <EmbeddedResource Include="Resources\Seed\pokemon\p12_pokemon.png" />
    <EmbeddedResource Include="Resources\Seed\pokemon\p13_pokemon.png" />
    <EmbeddedResource Include="Resources\Seed\pokemon\p14_pokemon.png" />
    <EmbeddedResource Include="Resources\Seed\pokemon\p15_pokemon.png" />
  </ItemGroup>

  <ItemGroup>
    <MauiFont Include="Resources\Fonts\Gwenchana\Gwenchana.ttf" />
    <MauiFont Include="wwwroot\fonts\Gwenchana.ttf" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Maui.Controls" Version="10.0.90" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebView.Maui" Version="10.0.90" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.11" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Localization" Version="10.0.11" />
    <PackageReference Include="MudBlazor" Version="9.8.0" />
    <PackageReference Include="Plugin.Maui.Audio" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="CommunityToolkit.Mvvm.ComponentModel" />
    <Using Include="CommunityToolkit.Mvvm.Input" />
    <Using Include="Microsoft.Extensions.Localization" />
    <Using Include="Microsoft.Extensions.Logging" />
    <Using Include="Plugin.Maui.Audio" />
    <Using Include="System.Collections.ObjectModel" />
  </ItemGroup>

  <ItemGroup>
    <MauiImage Include="wwwroot\images\back.png">
      <LogicalName>%(RecursiveDir)%(Filename)%(Extension)</LogicalName>
    </MauiImage>
    <MauiImage Include="wwwroot\images\empty.png">
      <LogicalName>%(RecursiveDir)%(Filename)%(Extension)</LogicalName>
    </MauiImage>
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\images\back.png" />
    <None Include="wwwroot\images\empty.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Localization\Strings.resx" />
    <EmbeddedResource Update="Resources\Localization\Strings.en-US.resx" />
    <EmbeddedResource Update="Resources\Localization\Strings.pt-BR.resx" />

  </ItemGroup>
</Project>
