<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <CollectCoverage>true</CollectCoverage>
    <CoverletOutputFormat>cobertura</CoverletOutputFormat>
    <CoverletOutput>
      $(MSBuildProjectDirectory)/TestResults/
    </CoverletOutput>
    <Include>
      [MemoAna.Backend]MemoAna.Backend.Controllers.*;
      [MemoAna.Backend.Application]MemoAna.Backend.Application.*;
      [MemoAna.Backend.Domain]MemoAna.Backend.Domain.*;
      [MemoAna.Backend.Infrastructure]MemoAna.Backend.Infrastructure.*
    </Include>
    <Exclude>
      [MemoAna.Backend]Microsoft.AspNetCore.OpenApi.Generated*,
      [MemoAna.Backend]Microsoft.AspNetCore.Components.*.g__*,
      [MemoAna.Backend]Microsoft.Extensions.*.g__*,
      [MemoAna.Backend]System.*
      [MemoAna.Backend.Composition]Mediator.*
      [Mediator.SourceGenerator]Mediator.*
    </Exclude>
    <Threshold>80</Threshold>
    <ThresholdType>line,branch</ThresholdType>
    <ThresholdStat>Total</ThresholdStat>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>
        runtime; build; native; contentfiles;analyzers; buildtransitive
      </IncludeAssets>
    </PackageReference>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Mediator.Abstractions" Version="3.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.11" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>
        runtime; build; native; contentfiles;analyzers; buildtransitive
      </IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference
      Include="..\..\..\src\web\MemoAna.Backend\MemoAna.Backend.csproj" />
    <ProjectReference
      Include="..\..\..\src\web\MemoAna.Backend.Application\MemoAna.Backend.Application.csproj" />
    <ProjectReference
      Include="..\..\..\src\web\MemoAna.Backend.Domain\MemoAna.Backend.Domain.csproj" />
    <ProjectReference
      Include="..\..\..\src\web\MemoAna.Backend.Infrastructure\MemoAna.Backend.Infrastructure.csproj" />
    <ProjectReference
      Include="..\..\..\src\web\MemoAna.Backend.Composition\MemoAna.Backend.Composition.csproj" />
  </ItemGroup>

</Project>