// <auto-generated />
using System;
using MemoAna.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MemoAna.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260605083639_AddGameStatisticsSet")]
    partial class AddGameStatisticsSet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("MemoAna.Domain.Entities.CardThemeEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Base64Images")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ManifestId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ManifestId")
                        .IsUnique();

                    b.ToTable("CardThemes");
                });

            modelBuilder.Entity("MemoAna.Domain.Entities.CardThemeManifestEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CardThemeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreviewBase64Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThemeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CardThemeManifests");
                });

            modelBuilder.Entity("MemoAna.Domain.Entities.GameStatisticsEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FinalScore")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVictory")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mistakes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RemainingSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SuccessfulMoves")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThemeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalMoves")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GameStatistics");
                });

            modelBuilder.Entity("MemoAna.Domain.Entities.CardThemeEntity", b =>
                {
                    b.HasOne("MemoAna.Domain.Entities.CardThemeManifestEntity", "Manifest")
                        .WithOne("CardTheme")
                        .HasForeignKey("MemoAna.Domain.Entities.CardThemeEntity", "ManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manifest");
                });

            modelBuilder.Entity("MemoAna.Domain.Entities.CardThemeManifestEntity", b =>
                {
                    b.Navigation("CardTheme");
                });
#pragma warning restore 612, 618
        }
    }
}
